In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [3]:
df =  pd.read_excel(r"C:\Users\mr.shoaib\Documents\Social Network Ads.xlsx")

In [4]:
df

    Age   Estimated Salary  Purchased
0     19            190000          0
1     35            240000          0
2     26             10000          0
3     27             20000          0
4     19             70000          0
5     27             60000          0
6     32             50000          0
7     25             55000          0
8     25             20000          1
9     25             33000          0
10    26             25000          0
11    26             40000          0
12    27             15000          0
13    87            430000          0
14    76             65000          0
15    67             90000          0
16    54            410000          0
17    67             22000          1
18    76             20000          1
19    32             67000          1
20    87             43000          1
21    65             99000          1
22    12             32000          1
23    35             47000          1
24    65             78000          1
25    76             88000          1
26    76             88000          1

In [5]:
df['Purchased'].value_counts()

Purchased
0    16
1    11
Name: count, dtype: int64

In [6]:
x = df.iloc[:,:-1]
y = df['Purchased']

In [7]:
#Apply to Random under sampler.

In [8]:
from imblearn.under_sampling import RandomUnderSampler

In [9]:
from imblearn.over_sampling import RandomOverSampler

In [10]:
ro = RandomOverSampler()
ro_x, ro_y = ro.fit_resample(x,y)

In [11]:
ro_x

    Age   Estimated Salary
0     19            190000
1     35            240000
2     26             10000
3     27             20000
4     19             70000
5     27             60000
6     32             50000
7     25             55000
8     25             20000
9     25             33000
10    26             25000
11    26             40000
12    27             15000
13    87            430000
14    76             65000
15    67             90000
16    54            410000
17    67             22000
18    76             20000
19    32             67000
20    87             43000
21    65             99000
22    12             32000
23    35             47000
24    65             78000
25    76             88000
26    76             88000
27    87             43000
28    76             88000
29    76             88000
30    65             78000
31    67             22000

In [12]:
ro_y

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     1
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
Name: Purchased, dtype: int64

In [13]:
ro_y.value_counts()

Purchased
0    16
1    16
Name: count, dtype: int64

In [14]:
x_train1,x_test1,y_train1,y_test1=train_test_split(ro_x, ro_y,test_size=0.2,random_state=42)

In [15]:
lr1 = LogisticRegression()
lr1.fit(x_train1, y_train1)

LogisticRegression()

In [16]:
lr1.score(x_test1, y_test1)*100

71.42857142857143

In [19]:
lr1.predict([[19,190000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [10]:
ru = RandomUnderSampler()
ru_x, ru_y = ru.fit_resample(x,y)

In [13]:
ru_y.value_counts()

Purchased
0    11
1    11
Name: count, dtype: int64

In [18]:
x_train,x_test,y_train,y_test=train_test_split(ru_x, ru_y,test_size=0.2,random_state=42)

In [21]:
lr = LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

In [22]:
lr.score(x_test,y_test)*100

80.0

In [25]:
lr.predict([[67,22000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [27]:
lr.predict([[19,190000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0], dtype=int64)