In [31]:
import pandas as pd

In [32]:
df = pd.read_csv(r"C:\Users\mr.shoaib\Downloads\groceries - groceries.csv")
df.head(2)

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.columns

Index(['Item(s)', 'Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5', 'Item 6',
       'Item 7', 'Item 8', 'Item 9', 'Item 10', 'Item 11', 'Item 12',
       'Item 13', 'Item 14', 'Item 15', 'Item 16', 'Item 17', 'Item 18',
       'Item 19', 'Item 20', 'Item 21', 'Item 22', 'Item 23', 'Item 24',
       'Item 25', 'Item 26', 'Item 27', 'Item 28', 'Item 29', 'Item 30',
       'Item 31', 'Item 32'],
      dtype='str')

In [34]:
df["Item 2"][0]

'semi-finished bread'

In [35]:
type(df["Item 2"][0])

str

In [36]:
df.shape

(9835, 33)

In [37]:
market = []
for i in range(0,df.shape[0]):
    cus = []
    for j in df.columns:
        if type(df[j][i])==str:
            cus.append(df[j][i])

    market.append(cus)

In [38]:
l = []
for i in market:
    for j in i:
        l.append(j)

In [39]:
l

['citrus fruit',
 'semi-finished bread',
 'margarine',
 'ready soups',
 'tropical fruit',
 'yogurt',
 'coffee',
 'whole milk',
 'pip fruit',
 'yogurt',
 'cream cheese',
 'meat spreads',
 'other vegetables',
 'whole milk',
 'condensed milk',
 'long life bakery product',
 'whole milk',
 'butter',
 'yogurt',
 'rice',
 'abrasive cleaner',
 'rolls/buns',
 'other vegetables',
 'UHT-milk',
 'rolls/buns',
 'bottled beer',
 'liquor (appetizer)',
 'potted plants',
 'whole milk',
 'cereals',
 'tropical fruit',
 'other vegetables',
 'white bread',
 'bottled water',
 'chocolate',
 'citrus fruit',
 'tropical fruit',
 'whole milk',
 'butter',
 'curd',
 'yogurt',
 'flour',
 'bottled water',
 'dishes',
 'beef',
 'frankfurter',
 'rolls/buns',
 'soda',
 'chicken',
 'tropical fruit',
 'butter',
 'sugar',
 'fruit/vegetable juice',
 'newspapers',
 'fruit/vegetable juice',
 'packaged fruit/vegetables',
 'chocolate',
 'specialty bar',
 'other vegetables',
 'butter milk',
 'pastry',
 'whole milk',
 'tropical fruit',
 'cream cheese',
 'processed cheese',
 'detergent',
 'newspapers',
 'tropical fruit',
 'root vegetables',
 'other vegetables',
 'frozen dessert',
 'rolls/buns',
 'flour',
 'sweet spreads',
 'salty snack',
 'waffles',
 'candy',
 'bathroom cleaner',
 'bottled water',
 'canned beer',
 'yogurt',
 'sausage',
 'rolls/buns',
 'soda',
 'chocolate',
 'other vegetables',
 'brown bread',
 'soda',
 'fruit/vegetable juice',
 'canned beer',
 'newspapers',
 'shopping bags',
 'yogurt',
 'beverages',
 'bottled water',
 'specialty bar',
 'hamburger meat',
 'other vegetables',
 'rolls/buns',
 'spices',
 'bottled water',
 'hygiene articles',
 'napkins',
 'root vegetables',
 'other vegetables',
 'whole milk',
 'beverages',
 'sugar',
 'pork',
 'berries',
 'other vegetables',
 'whole milk',
 'whipped/sour cream',
 'artif. sweetener',
 'soda',
 'abrasive cleaner',
 'beef',
 'grapes',
 'detergent',
 'pastry',
 'soda',
 'fruit/vegetable juice',
 'canned beer',
 'root vegetables',
 'other vegetables',
 'whole milk',
 'dessert',
 'citrus fruit',
 'zwieback',
 'newspapers',
 'sausage',
 'rolls/buns',
 'soda',
 'canned beer',
 'specialty bar',
 'shopping bags',
 'tropical fruit',
 'root vegetables',
 'whole milk',
 'yogurt',
 'domestic eggs',
 'brown bread',
 'pastry',
 'sugar',
 'cereals',
 'coffee',
 'soda',
 'waffles',
 'candy',
 'berries',
 'yogurt',
 'canned beer',
 'butter milk',
 'yogurt',
 'cream cheese',
 'spread cheese',
 'rolls/buns',
 'bottled water',
 'soda',
 'newspapers',
 'coffee',
 'pastry',
 'bottled water',
 'rolls/buns',
 'misc. beverages',
 'root vegetables',
 'other vegetables',
 'butter',
 'curd',
 'whipped/sour cream',
 'UHT-milk',
 'hard cheese',
 'rolls/buns',
 'bottled water',
 'long life bakery product',
 'sausage',
 'rolls/buns',
 'cat food',
 'newspapers',
 'canned beer',
 'ham',
 'grapes',
 'other vegetables',
 'whole milk',
 'turkey',
 'tropical fruit',
 'other vegetables',
 'curd',
 'domestic eggs',
 'brown bread',
 'semi-finished bread',
 'margarine',
 'baking powder',
 'fruit/vegetable juice',
 'whole milk',
 'yogurt',
 'processed cheese',
 'pickled vegetables',
 'soda',
 'whole milk',
 'curd',
 'yogurt',
 'pastry',
 'packaged fruit/vegetables',
 'brown bread',
 'canned beer',
 'rolls/buns',
 'oil',
 'bottled water',
 'chewing gum',
 'chocolate marshmallow',
 'hygiene articles',
 'napkins',
 'ham',
 'beef',
 'whipped/sour cream',
 'ice cream',
 'rolls/buns',
 'cat food',
 'rolls/buns',
 'pastry',
 'sugar',
 'other vegetables',
 'whole milk',
 'frozen vegetables',
 'canned fish',
 'salty snack',
 'seasonal products',
 'detergent',
 'sausage',
 'pastry',
 'sausage',
 'beef',
 'whole milk',
 'frankfurter',
 'tropical fruit',
 'rolls/buns',
 'brown bread',
 'sugar',
 'rolls/buns',
 'pastry',
 'soda',
 'whole milk',
 'curd cheese',
 'coffee',
 'red/blush wine',
 'newspapers',
 'sausage',
 'whole milk',
 'curd',
 'tropical fruit',
 'pip fruit',
 'berries',
 'whole milk',
 'frozen potato products',
 'rolls/buns',
 'pickled vegetables',
 'chocolate',
 'red/blush wine',
 'whole milk',
 'butter',
 'margarine',
 'specialty fat',
 'specialty chocolate',
 'candles',
 'flower (seeds)',
 'frankfurter',
 'citrus fruit',
 'whole milk',
 'domestic eggs',
 'oil',
 'sparkling wine',
 'specialty chocolate',
 'newspapers',
 'whole milk',
 'meat spreads',
 'soda',
 'frozen potato products',
 'other vegetables',
 'whole milk',
 'rolls/buns',
 'sugar',
 'citrus fruit',
 'whole milk',
 'curd',
 'butter milk',
 'pastry',
 'flour',
 'salt',
 'bottled water',
 'fruit/vegetable juice',
 'bottled beer',
 'sugar',
 'bottled water',
 'soda',
 'bottled beer',
 'frozen meals',
 'coffee',
 'chocolate',
 'root vegetables',
 'whole milk',
 'frozen vegetables',
 'domestic eggs',
 'rolls/buns',
 'oil',
 'margarine',
 'canned vegetables',
 'fruit/vegetable juice',
 'bathroom cleaner',
 'root vegetables',
 'onions',
 'hard cheese',
 'frozen vegetables',
 'herbs',
 'condensed milk',
 'frozen vegetables',
 'salt',
 'oil',
 'white wine',
 'candles',
 'bottled water',
 'sausage',
 'root vegetables',
 'onions',
 'yogurt',
 'rolls/buns',
 'brandy',
 'detergent',
 'coffee',
 'newspapers',
 'pork',
 'other vegetables',
 'whipped/sour cream',
 'berries',
 'yogurt',
 'soda',
 'berries',
 'fruit/vegetable juice',
 'salty snack',
 'candles',
 'citrus fruit',
 'butter milk',
 'yogurt',
 'cream cheese',
 'pork',
 'hamburger meat',
 'citrus fruit',
 'berries',
 'onions',
 'whipped/sour cream',
 'rice',
 'coffee',
 'chocolate',
 'detergent',
 'grapes',
 'photo/film',
 'sausage',
 'sliced cheese',
 'rolls/buns',
 'brown bread',
 'fruit/vegetable juice',
 'canned beer',
 'red/blush wine',
 'waffles',
 'shopping bags',
 'chicken',
 'hamburger meat',
 'citrus fruit',
 'tropical fruit',
 'root vegetables',
 'other vegetables',
 'butter',
 'pasta',
 'oil',
 'detergent',
 'whole milk',
 'yogurt',
 'brown bread',
 'citrus fruit',
 'tropical fruit',
 'soda',
 'misc. beverages',
 'sausage',
 'pork',
 'grapes',
 'whole milk',
 'rolls/buns',
 'pastry',
 'soda',
 'specialty bar',
 'bathroom cleaner',
 'frankfurter',
 'rolls/buns',
 'bottled water',
 'sausage',
 'whole milk',
 'yogurt',
 'coffee',
 'fruit/vegetable juice',
 'bottled beer',
 'softener',
 'napkins',
 'photo/film',
 'shopping bags',
 'soda',
 'rolls/buns',
 'fruit/vegetable juice',
 'beef',
 'citrus fruit',
 'berries',
 'root vegetables',
 'brown bread',
 'detergent',
 'whole milk',
 'whipped/sour cream',
 'rolls/buns',
 'soda',
 'waffles',
 'candy',
 'cling film/bags',
 'processed cheese',
 'tropical fruit',
 'pip fruit',
 'frankfurter',
 'sausage',
 'root vegetables',
 'other vegetables',
 'rolls/buns',
 'oil',
 'pickled vegetables',
 'bottled beer',
 'chewing gum',
 'dishes',
 'packaged fruit/vegetables',
 'bottled water',
 'whole milk',
 'dessert',
 'frozen vegetables',
 'rolls/buns',
 'margarine',
 'bottled water',
 'red/blush wine',
 'newspapers',
 'berries',
 'whipped/sour cream',
 'citrus fruit',
 'berries',
 'UHT-milk',
 'processed cheese',
 'tropical fruit',
 'whole milk',
 'yogurt',
 'hamburger meat',
 'whole milk',
 'frozen vegetables',
 'rolls/buns',
 'bottled beer',
 'sparkling wine',
 'hamburger meat',
 'other vegetables',
 'whole milk',
 'frozen vegetables',
 'domestic eggs',
 'soda',
 'dishes',
 'whole milk',
 'cream cheese',
 'soda',
 'fish',
 'other vegetables',
 'pastry',
 'margarine',
 'coffee',
 'long life bakery product',
 'male cosmetics',
 'shopping bags',
 'frankfurter',
 'sausage',
 'long life bakery product',
 'waffles',
 'packaged fruit/vegetables',
 'dessert',
 'semi-finished bread',
 'canned beer',
 'pastry',
 'soda',
 'other vegetables',
 'red/blush wine',
 'misc. beverages',
 'frankfurter',
 'sausage',
 'citrus fruit',
 'tropical fruit',
 'pip fruit',
 'whole milk',
 'hard cheese',
 'cream cheese',
 'domestic eggs',
 'rice',
 'sugar',
 'canned fruit',
 'misc. beverages',
 'fruit/vegetable juice',
 'hygiene articles',
 'sparkling wine',
 'specialty bar',
 'sausage',
 'butter milk',
 'rolls/buns',
 'curd cheese',
 'frankfurter',
 'dessert',
 'whole milk',
 'yogurt',
 'beverages',
 'brown bread',
 'shopping bags',
 'newspapers',
 'berries',
 'soda',
 'curd',
 'flour',
 'liquor (appetizer)',
 'tropical fruit',
 'other vegetables',
 'coffee',
 'soda',
 'rolls/buns',
 'Instant food products',
 'canned beer',
 'canned beer',
 'frankfurter',
 'sausage',
 'whole milk',
 'rolls/buns',
 'margarine',
 'other vegetables',
 'misc. beverages',
 'canned beer',
 'whole milk',
 'frozen vegetables',
 'whole milk',
 'citrus fruit',
 'butter',
 'cream cheese',
 'white bread',
 'oil',
 'margarine',
 'newspapers',
 'frankfurter',
 'rolls/buns',
 'frankfurter',
 'ham',
 'pip fruit',
 'other vegetables',
 'whole milk',
 'soft cheese',
 'frozen vegetables',
 'rolls/buns',
 'sugar',
 'baking powder',
 'butter milk',
 'yogurt',
 'honey',
 'soda',
 'detergent',
 'hamburger meat',
 'citrus fruit',
 'onions',
 'rolls/buns',
 'bottled water',
 'dental care',
 'pasta',
 'popcorn',
 'other vegetables',
 'whole milk',
 'meat spreads',
 'cake bar',
 'chocolate',
 'shopping bags',
 'sausage',
 'pork',
 'citrus fruit',
 'dessert',
 'white bread',
 'dishes',
 'candles',
 'rolls/buns',
 'grapes',
 'other vegetables',
 'curd',
 'dessert',
 'yogurt',
 'napkins',
 'root vegetables',
 'other vegetables',
 'whole milk',
 'yogurt',
 'beverages',
 'soft cheese',
 'frozen vegetables',
 'fruit/vegetable juice',
 'bottled beer',
 'coffee',
 'shopping bags',
 'popcorn',
 'whole milk',
 'rolls/buns',
 'sugar',
 'bottled water',
 'soda',
 'tropical fruit',
 'other vegetables',
 'packaged fruit/vegetables',
 'whole milk',
 'snack products',
 'beef',
 'herbs',
 'flour',
 'cling film/bags',
 'flower soil/fertilizer',
 'whole milk',
 'butter',
 'dessert',
 'rolls/buns',
 'frankfurter',
 'soda',
 'chewing gum',
 'tropical fruit',
 'specialty cheese',
 'bottled water',
 'canned beer',
 'finished products',
 'other vegetables',
 'frozen vegetables',
 'bottled beer',
 'beverages',
 'soda',
 'hamburger meat',
 'root vegetables',
 'whole milk',
 'whole milk',
 'pastry',
 'long life bakery product',
 'finished products',
 'white wine',
 'shopping bags',
 'other vegetables',
 'ham',
 'tropical fruit',
 'other vegetables',
 'whole milk',
 'white bread',
 'brown bread',
 'fruit/vegetable juice',
 'bottled beer',
 'other vegetables',
 'curd',
 'butter milk',
 'cocoa drinks',
 'salty snack',
 'popcorn',
 'bottled beer',
 'curd',
 'dessert',
 'soda',
 'salty snack',
 'waffles',
 'cake bar',
 'chocolate',
 'shopping bags',
 'whole milk',
 'cream cheese',
 'cereals',
 'dog food',
 'whole milk',
 'salt',
 'dessert',
 'ice cream',
 'sausage',
 'soft cheese',
 'coffee',
 'other vegetables',
 'bottled water',
 'waffles',
 'dishes',
 'shopping bags',
 'ham',
 'whole milk',
 'rolls/buns',
 'other vegetables',
 'ice cream',
 'other vegetables',
 'bottled water',
 'soda',
 'bottled beer',
 'white wine',
 'prosecco',
 'herbs',
 'candy',
 'frankfurter',
 'ham',
 'tropical fruit',
 'pip fruit',
 'root vegetables',
 'other vegetables',
 'whole milk',
 'butter',
 'curd',
 'yogurt',
 'whipped/sour cream',
 'soft cheese',
 'sliced cheese',
 'cream cheese',
 'frozen meals',
 'frozen fish',
 'domestic eggs',
 'white bread',
 'sugar',
 'cereals',
 'fruit/vegetable juice',
 'bottled beer',
 'waffles',
 'rolls/buns',
 'canned beer',
 'curd',
 'cream cheese',
 'semi-finished bread',
 'zwieback',
 'cake bar',
 'specialty bar',
 'shopping bags',
 'frankfurter',
 'tropical fruit',
 'whole milk',
 'spread cheese',
 'margarine',
 'shopping bags',
 'other vegetables',
 'dog food',
 'specialty bar',
 'curd',
 'salt',
 'liquor (appetizer)',
 'detergent',
 'shopping bags',
 'frankfurter',
 'rolls/buns',
 'soda',
 'beef',
 'berries',
 'root vegetables',
 'whole milk',
 'dessert',
 'spread cheese',
 'brown bread',
 'canned beer',
 'pork',
 'beef',
 'pip fruit',
 'herbs',
 'spices',
 'frankfurter',
 'citrus fruit',
 'UHT-milk',
 'margarine',
 'sugar',
 'sausage',
 'bottled beer',
 'liquor (appetizer)',
 'canned beer',
 'specialty chocolate',
 'curd',
 'rolls/buns',
 'canned beer',
 'whole milk',
 'bottled water',
 'newspapers',
 'rolls/buns',
 'chewing gum',
 'pork',
 'root vegetables',
 'other vegetables',
 'whole milk',
 'dishes',
 'citrus fruit',
 'pastry',
 'potted plants',
 'rolls/buns',
 'pastry',
 'soda',
 'butter',
 'yogurt',
 'bottled water',
 'soda',
 'make up remover',
 'hygiene articles',
 'condensed milk',
 'sugar',
 'coffee',
 'shopping bags',
 'sausage',
 'other vegetables',
 'yogurt',
 'soda',
 'shopping bags',
 'whole milk',
 'beverages',
 'UHT-milk',
 'soda',
 'sausage',
 'pork',
 'beef',
 'whole milk',
 'rolls/buns',
 'margarine',
 'beverages',
 'beverages',
 'specialty bar',
 'bottled water',
 'fruit/vegetable juice',
 'newspapers',
 'cleaner',
 'female sanitary products',
 'sausage',
 'soda',
 'newspapers',
 'shopping bags',
 'newspapers',
 'sausage',
 'beef',
 'citrus fruit',
 'other vegetables',
 'whole milk',
 'butter milk',
 'whipped/sour cream',
 'beverages',
 'hard cheese',
 'rolls/buns',
 'dish cleaner',
 'cookware',
 'misc. beverages',
 'newspapers',
 'white wine',
 'sausage',
 'sliced cheese',
 'rolls/buns',
 'soda',
 'canned beer',
 'shopping bags',
 'meat',
 'curd',
 'bottled beer',
 'cake bar',
 'frankfurter',
 'meat',
 'tropical fruit',
 'onions',
 'oil',
 'baking powder',
 'tea',
 'cling film/bags',
 'ice cream',
 'rolls/buns',
 'canned beer',
 'canned beer',
 'tropical fruit',
 'berries',
 'root vegetables',
 'other vegetables',
 'bottled water',
 'shopping bags',
 'meat',
 'citrus fruit',
 'other vegetables',
 'curd',
 'dessert',
 'butter milk',
 'beverages',
 'cream cheese',
 'rolls/buns',
 'brown bread',
 'tea',
 'bottled water',
 'whole milk',
 'mustard',
 'bottled water',
 'sausage',
 'beef',
 'beverages',
 'sliced cheese',
 'rolls/buns',
 'spices',
 'house keeping products',
 'flower (seeds)',
 'frankfurter',
 'sausage',
 'root vegetables',
 'butter',
 'curd',
 'sliced cheese',
 'rolls/buns',
 'salty snack',
 'long life bakery product',
 'meat',
 'other vegetables',
 'butter',
 'rolls/buns',
 'root vegetables',
 'beverages',
 'Instant food products',
 'pickled vegetables',
 'detergent',
 'root vegetables',
 'herbs',
 'other vegetables',
 'whole milk',
 'sliced cheese',
 'rolls/buns',
 'whole milk',
 'whipped/sour cream',
 'semi-finished bread',
 'margarine',
 'citrus fruit',
 'whole milk',
 'curd',
 'dessert',
 'yogurt',
 'whipped/sour cream',
 'frozen dessert',
 'rolls/buns',
 'salt',
 'sugar',
 'cereals',
 'canned vegetables',
 'canned fish',
 'skin care',
 'hygiene articles',
 'napkins',
 'citrus fruit',
 'curd',
 'pastry',
 'margarine',
 'sugar',
 'candy',
 'newspapers',
 'other vegetables',
 'whole milk',
 'bottled water',
 'soda',
 'misc. beverages',
 'bottled beer',
 'red/blush wine',
 'napkins',
 'citrus fruit',
 'whole milk',
 'rolls/buns',
 'sausage',
 'oil',
 'hygiene articles',
 'napkins',
 'frankfurter',
 'beef',
 'hamburger meat',
 'grapes',
 'root vegetables',
 'whole milk',
 'butter',
 'frozen dessert',
 'potato products',
 'bottled water',
 'bottled beer',
 'hard cheese',
 'rolls/buns',
 'bottled water',
 'newspapers',
 'cream cheese',
 'rolls/buns',
 'soda',
 'chocolate',
 'turkey',
 'beef',
 'frozen vegetables',
 'dishes',
 'photo/film',
 'pork',
 'other vegetables',
 'whipped/sour cream',
 'rolls/buns',
 'soda',
 'shopping bags',
 'whole milk',
 'beverages',
 'rolls/buns',
 'soda',
 'sausage',
 'pip fruit',
 'whole milk',
 'curd',
 'yogurt',
 ...]

In [40]:
import collections

In [41]:
p = collections.Counter(l)

In [42]:
d = {"Item Name":p.keys(),"values":p.values()}

In [43]:
pd.DataFrame(d).sort_values(by=["values"],ascending=False)

                 Item Name  values
7               whole milk    2513
11        other vegetables    1903
17              rolls/buns    1809
31                    soda    1715
5                   yogurt    1372
..                     ...     ...
164                   bags       4
167        kitchen utensil       4
168  preservation products       2
159              baby food       1
166   sound storage medium       1

[169 rows x 2 columns]

In [23]:
from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [29]:
tr = TransactionEncoder()
tr.fit(market)

TransactionEncoder()

In [44]:
df = pd.DataFrame(tr.transform(market),columns=tr.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [45]:
from mlxtend.frequent_patterns import apriori

In [48]:
apriori(df,min_support=0.07,use_colnames=True,max_len=3).sort_values(by=["support"])

     support                                   itemsets
15  0.071683            frozenset({whipped/sour cream})
4   0.072293         frozenset({fruit/vegetable juice})
18  0.074835  frozenset({whole milk, other vegetables})
8   0.075648                     frozenset({pip fruit})
2   0.077682                   frozenset({canned beer})
5   0.079817                    frozenset({newspapers})
0   0.080529                  frozenset({bottled beer})
3   0.082766                  frozenset({citrus fruit})
7   0.088968                        frozenset({pastry})
11  0.093950                       frozenset({sausage})
12  0.098526                 frozenset({shopping bags})
14  0.104931                frozenset({tropical fruit})
10  0.108998               frozenset({root vegetables})
1   0.110524                 frozenset({bottled water})
17  0.139502                        frozenset({yogurt})
13  0.174377                          frozenset({soda})
9   0.183935                    frozenset({rolls/buns})
6   0.193493              frozenset({other vegetables})
16  0.255516                    frozenset({whole milk})