In [1]:
import pandas as pd

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.read_csv(r"C:\Users\mr.shoaib\Downloads\home_prices (1).csv")

In [4]:
df

         locality  area_sqr_ft  price_lakhs  bedrooms
0          Kollur          656         39.0         2
1          Kollur         1260         83.2         2
2          Kollur         1057         86.6         3
3          Kollur         1259         59.0         2
4          Kollur         1800        140.0         3
5          Kollur         1325         80.1         2
6          Kollur         1085        116.0         3
7          Kollur         1110         45.0         2
8          Kollur         1700        100.0         3
9   Banjara Hills         1650        200.0         3
10  Banjara Hills         2438        316.0         3
11  Banjara Hills         2115        220.0         2
12  Banjara Hills         1600        150.0         3
13  Banjara Hills         2400        300.0         3
14  Banjara Hills         1100         85.0         2
15  Banjara Hills         2600        400.0         3
16        Mankhal         1100         54.0         2
17        Mankhal         1125         64.0         2
18        Mankhal         1008         50.0         2
19        Mankhal         1266         78.0         2
20        Mankhal         1540         94.0         3
21        Mankhal         1200         85.0         3

In [5]:
cat_cols = ['locality']

In [6]:
cat_cols

['locality']

In [7]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [8]:
encoder

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [9]:
encoded_array = encoder.fit_transform(df[cat_cols])

In [10]:
encoded_array

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [12]:
encoded_df = pd.DataFrame(encoded_array,columns=encoder.get_feature_names_out(cat_cols))

In [13]:
encoded_df

    locality_Banjara Hills  locality_Kollur  locality_Mankhal
0                      0.0              1.0               0.0
1                      0.0              1.0               0.0
2                      0.0              1.0               0.0
3                      0.0              1.0               0.0
4                      0.0              1.0               0.0
5                      0.0              1.0               0.0
6                      0.0              1.0               0.0
7                      0.0              1.0               0.0
8                      0.0              1.0               0.0
9                      1.0              0.0               0.0
10                     1.0              0.0               0.0
11                     1.0              0.0               0.0
12                     1.0              0.0               0.0
13                     1.0              0.0               0.0
14                     1.0              0.0               0.0
15                     1.0              0.0               0.0
16                     0.0              0.0               1.0
17                     0.0              0.0               1.0
18                     0.0              0.0               1.0
19                     0.0              0.0               1.0
20                     0.0              0.0               1.0
21                     0.0              0.0               1.0

In [14]:
encoded_df.index = df.index

In [15]:
encoded_df

    locality_Banjara Hills  locality_Kollur  locality_Mankhal
0                      0.0              1.0               0.0
1                      0.0              1.0               0.0
2                      0.0              1.0               0.0
3                      0.0              1.0               0.0
4                      0.0              1.0               0.0
5                      0.0              1.0               0.0
6                      0.0              1.0               0.0
7                      0.0              1.0               0.0
8                      0.0              1.0               0.0
9                      1.0              0.0               0.0
10                     1.0              0.0               0.0
11                     1.0              0.0               0.0
12                     1.0              0.0               0.0
13                     1.0              0.0               0.0
14                     1.0              0.0               0.0
15                     1.0              0.0               0.0
16                     0.0              0.0               1.0
17                     0.0              0.0               1.0
18                     0.0              0.0               1.0
19                     0.0              0.0               1.0
20                     0.0              0.0               1.0
21                     0.0              0.0               1.0

In [16]:
df = df.drop(cat_cols, axis=1)

In [17]:
df

    area_sqr_ft  price_lakhs  bedrooms
0           656         39.0         2
1          1260         83.2         2
2          1057         86.6         3
3          1259         59.0         2
4          1800        140.0         3
5          1325         80.1         2
6          1085        116.0         3
7          1110         45.0         2
8          1700        100.0         3
9          1650        200.0         3
10         2438        316.0         3
11         2115        220.0         2
12         1600        150.0         3
13         2400        300.0         3
14         1100         85.0         2
15         2600        400.0         3
16         1100         54.0         2
17         1125         64.0         2
18         1008         50.0         2
19         1266         78.0         2
20         1540         94.0         3
21         1200         85.0         3

In [18]:
df = pd.concat([df, encoded_df], axis=1)

In [19]:
df

,area_sqr_ft,price_lakhs,bedrooms,locality_Banjara Hills,locality_Kollur,locality_Mankhal
0,656,39.0,2,0.0,1.0,0.0
1,1260,83.2,2,0.0,1.0,0.0
2,1057,86.6,3,0.0,1.0,0.0
3,1259,59.0,2,0.0,1.0,0.0
4,1800,140.0,3,0.0,1.0,0.0
5,1325,80.1,2,0.0,1.0,0.0
6,1085,116.0,3,0.0,1.0,0.0
7,1110,45.0,2,0.0,1.0,0.0
8,1700,100.0,3,0.0,1.0,0.0
9,1650,200.0,3,1.0,0.0,0.0
10,2438,316.0,3,1.0,0.0,0.0
11,2115,220.0,2,1.0,0.0,0.0
12,1600,150.0,3,1.0,0.0,0.0
13,2400,300.0,3,1.0,0.0,0.0
14,1100,85.0,2,1.0,0.0,0.0
15,2600,400.0,3,1.0,0.0,0.0
16,1100,54.0,2,0.0,0.0,1.0
17,1125,64.0,2,0.0,0.0,1.0
18,1008,50.0,2,0.0,0.0,1.0
19,1266,78.0,2,0.0,0.0,1.0
20,1540,94.0,3,0.0,0.0,1.0
21,1200,85.0,3,0.0,0.0,1.0

In [20]:
df.head(5)

,area_sqr_ft,price_lakhs,bedrooms,locality_Banjara Hills,locality_Kollur,locality_Mankhal
0,656,39.0,2,0.0,1.0,0.0
1,1260,83.2,2,0.0,1.0,0.0
2,1057,86.6,3,0.0,1.0,0.0
3,1259,59.0,2,0.0,1.0,0.0
4,1800,140.0,3,0.0,1.0,0.0