In [58]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [59]:
df =  pd.read_csv(r"C:\Users\mr.shoaib\Downloads\student_scores.csv")

In [60]:
df

    cgpa  scores  placed
0   8.41      20       0
1   9.61      90       0
2   7.63      58       0
3   6.47      31       0
4   5.48       5       0
..   ...     ...     ...
95  5.40      26       1
96  5.70      32       1
97  4.80      25       1
98  1.20       3       0
99  2.00       8       0

[100 rows x 3 columns]

In [61]:
df.isnull()

     cgpa  scores  placed
0   False   False   False
1   False   False   False
2   False   False   False
3   False   False   False
4   False   False   False
..    ...     ...     ...
95  False   False   False
96  False   False   False
97  False   False   False
98  False   False   False
99  False   False   False

[100 rows x 3 columns]

In [62]:
x = df.iloc[:,:-1]
y = df["placed"]

In [63]:
x

    cgpa  scores
0   8.41      20
1   9.61      90
2   7.63      58
3   6.47      31
4   5.48       5
..   ...     ...
95  5.40      26
96  5.70      32
97  4.80      25
98  1.20       3
99  2.00       8

[100 rows x 2 columns]

In [64]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    0
99    0
Name: placed, Length: 100, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [67]:
from sklearn.metrics import accuracy_score

In [68]:
from sklearn.neighbors import KNeighborsClassifier

In [74]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [75]:
model.score(x_test, y_test)*100

35.0

In [76]:
y_pred = model.predict(x_test)

In [77]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0],
      dtype=int64)

In [78]:
acc = accuracy_score(y_test, y_pred)
acc

0.35